name: build

on:
  push:
    branches: [ "master", "github-automation" ]
  workflow_dispatch:

jobs:
  lexicon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.8
      - name: Install modules
        run: pip3 install requests
      - name: Generate lexicon file
        run: python3 gdoc_to_tex.py
        env:
          DOC_ID: ${{ secrets.DOC_ID }}
          TAB_ID: ${{ secrets.TAB_ID }}
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive latexmk
      - name: Compile LaTeX
        working-directory: .
        run: xelatex -synctex=1 -interaction=nonstopmode *.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Grammar
          path: lang2.pdf